default:		# Target 
- module1*	# Dependency 1 (contains main)
- module2		# Dependency 2
target1:		# Target
- module3		# Dependency 1
- module4		# Dependency 2
target2:		# Target
- module3		# Dependency 1
- module5*	# Dependency 2 (contains main)
- target1		# Dependency 3 (implies target1 is a lib/shared lib)
